#!/bin/sh

GOTKSYNC="./clusters/cluster1/flux-system/gotk-sync.yaml"

echo "# This manifest was generated by flux. DO NOT EDIT." > $GOTKSYNC

flux create source git k8-fcos-gitops \
    --url=https://github.com/dcatwoohoo/k8-fcos-gitops \
    --branch=main \
    --interval=3m \
    --export >> $GOTKSYNC

flux create kustomization k8-fcos-gitops \
    --source=k8-fcos-gitops \
    --path="./clusters/cluster1/" \
    --prune=true \
    --interval=5m \
    --export >> $GOTKSYNC
