---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8-fcos-gitops
  namespace: flux-system
spec:
  interval: 3m0s
  ref:
    branch: main
  url: https://github.com/dcatwoohoo/k8-fcos-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: k8-fcos-gitops
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/cluster1
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8-fos-gitops
